name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: Install modules
        run: pnpm install
      - name: Run Lint
        run: cd packages/smarty-ui-vite2 && pnpm run lint
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: cd packages/smarty-ui-vite2 && pnpm run test:run